language: c
install: sudo apt-get install polyml libpolyml-dev && compiler/build/install-deps.sh
sudo: required
script: ulimit -Sv 2970000 && Holmake all
env: PATH=$HOME/HOL/bin:$HOME/latexmk:$PATH:$HOME/HOL/bin
cache:
  directories:
    - $HOME/HOL
notifications:
  email: false
addons:
  apt:
    packages:
    - texlive
    - texlive-latex-extra
    - lmodern
